package ua.univercity;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Arrays;
import java.util.List;
import java.util.function.Predicate;

public class Main {
    public static void main(String[] args) {
        //! === TASK ONE ===
        System.out.println("\n\n=== TASK ONE ===");

        ZoneId kyivZone = ZoneId.of("Europe/Kiev");

        // Init events
        Event e1 = new Event("First Event", LocalDateTime.of(2026, 3, 25, 10, 0), 60, kyivZone, "Track A");
        Event e2 = new Event("Second Event", LocalDateTime.of(2026, 3, 25, 11, 30), 45, kyivZone, "Track B");

        // Test methods
        System.out.println(e1.label() + " ends at: " + e1.end());
        System.out.println(e2.label() + " ends at: " + e2.end());

        //! === TASK TWO ===
        System.out.println("\n\n=== TASK TWO ===");

        ZoneId londonZone = ZoneId.of("Europe/London");

        List<Event> schedule = Arrays.asList(
                new Event("First Event", LocalDateTime.of(2026, 3, 25, 10, 0), 60, kyivZone, "Track A"),
                new Event("Second Event", LocalDateTime.of(2026, 3, 25, 11, 30), 45, kyivZone, "Track B"),
                new Event("Third Event", LocalDateTime.of(2026, 3, 25, 9, 30), 90, kyivZone, "Track A"),
                new Event("Fourth Event (London)", LocalDateTime.of(2026, 3, 25, 15, 0), 30, londonZone, "Track C")
        );

        Predicate<Event> isMorning = e -> e.getStart().getHour() < 12;

        Predicate<Event> isLongEvent = e -> e.getDurationMinutes() > 50;

        Predicate<Event> morningAndShort = isMorning.and(isLongEvent.negate());


        System.out.println("| Morning not long Events");
        List<Event> filtered = EventLab.pick(schedule, morningAndShort);
        EventLab.notifyAll(filtered, e -> System.out.println("Picked: " + e.label()));


        Event customEvent = EventLab.create(() ->
                new Event("Lunch Break", LocalDateTime.of(2026, 3, 25, 13, 0), 60, kyivZone, "Food")
        );
        System.out.println("\nGenerated by supplier: " + customEvent.label());

        EventLab.findConflicts(schedule);

        //! === TASK THREE ===
        System.out.println("\n\n=== TASK THREE ===");

        // Init Events
        List<Event> schedule1 = Arrays.asList(
                new Event("B First Event", LocalDateTime.of(2026, 3, 25, 10, 0), 60, kyivZone, "Track A"),
                new Event("C Second Event", LocalDateTime.of(2026, 3, 25, 11, 30), 45, kyivZone, "Track B"),
                new Event("A Third Event", LocalDateTime.of(2026, 3, 25, 9, 30), 90, kyivZone, "Track A")
        );

        System.out.println("| Anonymous class");
        LambdaRefactorLab.sortAnonymous(schedule1);
        EventLab.notifyAll(schedule1, e -> System.out.println(e.label()));

        // Mix order
        List<Event> schedule2 = Arrays.asList(
                new Event("A First Event", LocalDateTime.of(2026, 3, 25, 10, 0), 60, kyivZone, "Track A"),
                new Event("C Second", LocalDateTime.of(2026, 3, 25, 11, 30), 45, kyivZone, "Track B"),
                new Event("B Third Event", LocalDateTime.of(2026, 3, 25, 9, 30), 90, kyivZone, "Track A")
        );

        System.out.println("\n| Lambda");
        LambdaRefactorLab.sortLambda(schedule2);
        EventLab.notifyAll(schedule2, e -> System.out.println(e.label()));

        List<Event> schedule3 = Arrays.asList(
                new Event("B First Event", LocalDateTime.of(2026, 3, 25, 10, 0), 60, kyivZone, "Track A"),
                new Event("A Second Event", LocalDateTime.of(2026, 3, 25, 11, 30), 45, kyivZone, "Track B"),
                new Event("C Third Event", LocalDateTime.of(2026, 3, 25, 9, 30), 90, kyivZone, "Track A")
        );

        System.out.println("\n| Method Reference");
        LambdaRefactorLab.sortMethodRef(schedule3);
        EventLab.notifyAll(schedule3, e -> System.out.println(e.label()));

    }
}